server:
  port: 8888
spring:
  application:
    name: wx
  datasource:
    url: jdbc:mysql://47.119.152.95:3306/wx?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #配置rabbitMQ服务器
  rabbitmq:
    host: 47.119.152.95
    port: 5672
    username: guest
    password: guest
    virtual-host: wx
logging:
  level:
    com: debug
wx:
  loginUrl: https://api.weixin.qq.com/sns/jscode2session
  appId: wx2cc7e47c681d1101
  appSecret: f82ac985066a669e42def2f77e0e8b30